In [45]:
import numpy as np

x=np.array([2,0,2,3,2,0,0,7,6])
x=x.reshape([3,3])
print(x)

[[2 0 2]
 [3 2 0]
 [0 7 6]]


In [46]:
transform=x.T
print(transform)

[[2 3 0]
 [0 2 7]
 [2 0 6]]


In [47]:
print(x)
a=np.linalg.inv(x)
print(a)

[[2 0 2]
 [3 2 0]
 [0 7 6]]
[[ 0.18181818  0.21212121 -0.06060606]
 [-0.27272727  0.18181818  0.09090909]
 [ 0.31818182 -0.21212121  0.06060606]]


In [48]:
getline=x[[0,2],:]
print(getline)

[[2 0 2]
 [0 7 6]]


In [49]:
mult=transform*x
print(mult)

[[ 4  0  0]
 [ 0  4  0]
 [ 0  0 36]]


In [50]:
reverse=x[::-1]
print(reverse)

[[0 7 6]
 [3 2 0]
 [2 0 2]]
